# Generated by Django 5.0.3 on 2024-03-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovo', '0002_alter_usuario_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='ponto_de_referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
