# Generated by Django 5.0.3 on 2024-03-13 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovo', '0003_alter_endereco_complemento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id_restaurante', models.AutoField(primary_key=True, serialize=False)),
                ('nome_restaurante', models.CharField(max_length=50)),
                ('sobre', models.CharField(blank=True, max_length=200, null=True)),
                ('endereco', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('horario_funcionamento', models.CharField(blank=True, max_length=150)),
                ('tipo_entrega_restaurante', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.CharField(max_length=50)),
                ('preco', models.BooleanField()),
                ('id_restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovo.restaurante')),
            ],
        ),
    ]
