# Generated by Django 5.0.3 on 2024-03-13 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovo', '0004_restaurante_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_entrega',
            fields=[
                ('id_tipo_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('nome_tipo_entrega', models.CharField(max_length=45)),
                ('tarifa', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='tipo_entrega_restaurante',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='id_tipo_entrega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ovo.tipo_entrega'),
        ),
    ]
