# Generated by Django 5.0.3 on 2024-03-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovo', '0005_tipo_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tipo_entrega',
            name='tarifa',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
