# Generated by Django 5.0.3 on 2024-03-19 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovo', '0006_alter_produto_preco_alter_tipo_entrega_tarifa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='id_restaurante',
            new_name='restaurante',
        ),
    ]
