# Generated by Django 5.0.3 on 2024-03-19 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovo', '0007_rename_id_restaurante_produto_restaurante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='restaurante',
            new_name='id_restaurante',
        ),
    ]
