# Generated by Django 5.0.3 on 2024-03-27 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovo', '0009_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPagamento',
            fields=[
                ('id_tipo_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id_comanda', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovo.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovo.restaurante')),
                ('id_tipo_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovo.tipo_entrega')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovo.usuario')),
                ('id_tipo_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovo.tipopagamento')),
            ],
        ),
    ]
