# Generated by Django 5.0.3 on 2024-04-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovo', '0011_pedido_id_comanda_alter_usuario_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(default='Inativo', max_length=30),
        ),
    ]
