# Generated by Django 5.0.3 on 2024-04-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovo', '0012_pedido_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comanda',
            old_name='id_comanda',
            new_name='id',
        ),
        migrations.AddField(
            model_name='comanda',
            name='num_comanda',
            field=models.IntegerField(default=0),
        ),
    ]
