# Generated by Django 5.0.3 on 2024-04-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovo', '0013_rename_id_comanda_comanda_id_comanda_num_comanda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comanda',
            old_name='id',
            new_name='id_comanda',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='id_produto',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='num_comanda',
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='comanda',
            name='produtos',
            field=models.JSONField(default=dict),
        ),
    ]
