# Generated by Django 5.0.6 on 2024-05-25 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovo', '0014_rename_id_comanda_id_comanda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id_cartao', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cartao', models.CharField(max_length=16)),
                ('data_validade', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('cpf_cnpj_titular', models.CharField(max_length=14)),
                ('apelido_cartao', models.CharField(blank=True, max_length=45, null=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ovo.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ovo.cartao'),
        ),
    ]
