# Generated by Django 5.0.6 on 2024-05-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovo', '0015_cartao_pedido_id_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='nome_titular',
            field=models.CharField(default='Sem nome', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartao',
            name='apelido_cartao',
            field=models.CharField(max_length=45),
        ),
    ]
