# Generated by Django 5.0.6 on 2024-05-28 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovo', '0016_cartao_nome_titular_alter_cartao_apelido_cartao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='nome_da_rua',
            new_name='longradouro',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='favorito',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='endereco',
        ),
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(default=None, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='cep',
            field=models.CharField(default=None, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(default=None, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='id_restaurante',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='ovo.restaurante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='pais',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='tipo_endereco',
            field=models.CharField(default='Residencial', max_length=45),
        ),
        migrations.AddField(
            model_name='endereco',
            name='uf',
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='id_usuario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ovo.usuario'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
