# Generated by Django 5.0.6 on 2024-05-28 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovo', '0017_rename_nome_da_rua_endereco_longradouro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='id_restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ovo.restaurante'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ovo.usuario'),
        ),
    ]
