# Generated by Django 5.0.6 on 2024-05-28 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovo', '0018_alter_endereco_id_restaurante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='longradouro',
            new_name='logradouro',
        ),
    ]
