# Generated by Django 5.0.2 on 2024-05-30 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovo', '0015_pedido_data'),
        ('ovo', '0019_rename_longradouro_endereco_logradouro'),
    ]

    operations = [
    ]
