# Generated by Django 5.0.3 on 2024-05-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovo', '0021_alter_endereco_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(max_length=45),
        ),
    ]
