# Generated by Django 5.0.3 on 2024-05-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovo', '0022_alter_endereco_bairro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(default='Bairro', max_length=45),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(default='nada', max_length=8),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(default='nada', max_length=45),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(default='nada', max_length=100),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='pais',
            field=models.CharField(default='nada', max_length=2),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='uf',
            field=models.CharField(default='nada', max_length=2),
        ),
    ]
